### ISSUE TITLE
Server not stopping

### ISSUE THREAD

**Issue by Fireeyeeian** [SuperRicky14/TpaPlusPlus#4]
When tpaplusplus is installed to my server and I send the stop command it won't get past `[Server thread/INFO]: JDA shut-down gracefully` when I disable the mod it stops just fine, no issue.

Server version: `Fabric 1.20.1`

If needed, I can give more info.

**Comment by SuperRicky14** [comment]
This issue has been fixed as of commit #d18084f; A release with this patch implemented is on it's way to Modrinth / Curseforge, thank you for reporting this issue!
