### ISSUE TITLE
[Bug]: No command /tpblock | There is no effect when time up

### ISSUE THREAD

**Issue by half-nothing** [SuperRicky14/TpaPlusPlus#5]
### Minecraft Version

1.20.4

### Mod Loader

Fabric

### Mod Loader Version

0.15.11

### Architectury API Version

11.1.17

### FCAPI Port (if present) Version

20.4.3

### Describe the bug

1. No command /tpblock
2. There is no tp when time up

### Steps to Reproduce

1. Edit config to add delay on command '/tpaaccept'
2. Send tpa request
3. Accept request
4. no effect when time up

### Crash Reports/Logs

no crash log

### Screenhots

![image](https://github.com/SuperRicky14/TpaPlusPlus/assets/50048293/a843b2ba-6407-4a71-b6d2-c09acaad471c)
![image](https://github.com/SuperRicky14/TpaPlusPlus/assets/50048293/2be93bbd-d046-468a-b12d-933ca118f149)

### Mod List

https://pastebin.com/VM5qPAnj

**Comment by half-nothing** [comment]
issue 1 is caused by:
![image](https://github.com/SuperRicky14/TpaPlusPlus/assets/50048293/649480de-2b61-43da-96d8-c7d289fd7291)
it should be TPBLOCK_COMMAND_NAME not TPUNBLOCK_COMMAND_NAME

**Comment by half-nothing** [comment]
new issue found:
command /tpblock has no effect
![image](https://github.com/SuperRicky14/TpaPlusPlus/assets/50048293/2b71f6bd-8705-4575-bf19-f11a2a764bbd)
And there is no error message from the console
![image](https://github.com/SuperRicky14/TpaPlusPlus/assets/50048293/839172de-0d8c-4297-acc6-5387d4fdff9d)

**Comment by half-nothing** [comment]
> new issue found: command /tpblock has no effect ![image](https://private-user-images.githubusercontent.com/50048293/335861401-2b71f6bd-8705-4575-bf19-f11a2a764bbd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTczMjgyODUsIm5iZiI6MTcxNzMyNzk4NSwicGF0aCI6Ii81MDA0ODI5My8zMzU4NjE0MDEtMmI3MWY2YmQtODcwNS00NTc1LWJmMTktZjExYTJhNzY0YmJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjAyVDExMzMwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM4NzY3YTk2YjZkZjE2ZDIyYmFhZTgwNzlmNTY0NWI1ZDQzYTFiMzA4NjBjNjdkYTkyYzE5ZWZlYzczZWE3OTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DCfDe9pg3LWC501wwJjCNAWRGZGZnVAsfzmQbNTjhlw) And there is no error message from the console ![image](https://private-user-images.githubusercontent.com/50048293/335861429-839172de-0d8c-4297-acc6-5387d4fdff9d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTczMjgyODUsIm5iZiI6MTcxNzMyNzk4NSwicGF0aCI6Ii81MDA0ODI5My8zMzU4NjE0MjktODM5MTcyZGUtMGQ4Yy00Mjk3LWFjYzYtNTM4N2Q0ZmRmZjlkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjAyVDExMzMwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFlNTY2N2JlYzk1MmJiZjMyM2FjNGM2Zjc2NjRhZjRlMjE5OTQ1NzZkYzEzM2JlNmRlZTc2Y2UzMTY3NDdlYTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HMYDWKs472zInYBQLpWHc9p32t0BqpKXd8C4NLBJwPQ)

this issue is caused by:
![image](https://github.com/SuperRicky14/TpaPlusPlus/assets/50048293/3fb4da31-10cb-4f3a-a5a9-09f58a55002b)
This function return a immutable list
So this will throw an exception
![image](https://github.com/SuperRicky14/TpaPlusPlus/assets/50048293/b4e87095-7941-4b09-96fc-2cdcbb211d68)

**Comment by half-nothing** [comment]
> > new issue found: command /tpblock has no effect ![image](https://private-user-images.githubusercontent.com/50048293/335861401-2b71f6bd-8705-4575-bf19-f11a2a764bbd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTczMjgyODUsIm5iZiI6MTcxNzMyNzk4NSwicGF0aCI6Ii81MDA0ODI5My8zMzU4NjE0MDEtMmI3MWY2YmQtODcwNS00NTc1LWJmMTktZjExYTJhNzY0YmJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjAyVDExMzMwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM4NzY3YTk2YjZkZjE2ZDIyYmFhZTgwNzlmNTY0NWI1ZDQzYTFiMzA4NjBjNjdkYTkyYzE5ZWZlYzczZWE3OTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DCfDe9pg3LWC501wwJjCNAWRGZGZnVAsfzmQbNTjhlw) And there is no error message from the console ![image](https://private-user-images.githubusercontent.com/50048293/335861429-839172de-0d8c-4297-acc6-5387d4fdff9d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTczMjgyODUsIm5iZiI6MTcxNzMyNzk4NSwicGF0aCI6Ii81MDA0ODI5My8zMzU4NjE0MjktODM5MTcyZGUtMGQ4Yy00Mjk3LWFjYzYtNTM4N2Q0ZmRmZjlkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjAyVDExMzMwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFlNTY2N2JlYzk1MmJiZjMyM2FjNGM2Zjc2NjRhZjRlMjE5OTQ1NzZkYzEzM2JlNmRlZTc2Y2UzMTY3NDdlYTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HMYDWKs472zInYBQLpWHc9p32t0BqpKXd8C4NLBJwPQ)
> 
> this issue is caused by: ![image](https://private-user-images.githubusercontent.com/50048293/335861890-3fb4da31-10cb-4f3a-a5a9-09f58a55002b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTczMjg3MDksIm5iZiI6MTcxNzMyODQwOSwicGF0aCI6Ii81MDA0ODI5My8zMzU4NjE4OTAtM2ZiNGRhMzEtMTBjYi00ZjNhLWE1YTktMDlmNThhNTUwMDJiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjAyVDExNDAwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVjMzY0MzEyZmIyNThmMjlmZmQyZTU2ODI2ZGI1YTMyM2UwNTQ3NDgxYTdlNzliNmJiMzc3NzliMjAxNGNjMDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZxroOJEFMTDdMAuNAf7NGY5-wO52aO-GorfSOYtdhho) This function return a immutable list So this will throw an exception ![image](https://private-user-images.githubusercontent.com/50048293/335861974-b4e87095-7941-4b09-96fc-2cdcbb211d68.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTczMjg3MDksIm5iZiI6MTcxNzMyODQwOSwicGF0aCI6Ii81MDA0ODI5My8zMzU4NjE5NzQtYjRlODcwOTUtNzk0MS00YjA5LTk2ZmMtMmNkY2JiMjExZDY4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjAyVDExNDAwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEzMWM0OWM0OTZhZTgzNjFkMWE0MjM3MzRkMzA0OGRmNzU3YjkzNmU4NDQwMmEwMjUzMTBjN2IxODBjZWQ5N2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ugqyNqNgD9mZxgVRGFKoI92GWL2lUEVDzoBOnuzVdR4)

the same as the /tpunblock command

**Comment by half-nothing** [comment]
issue 2 is a stupid error:
![image](https://github.com/SuperRicky14/TpaPlusPlus/assets/50048293/da7df0c5-7277-404d-b55e-b5634220bee5)
![image](https://github.com/SuperRicky14/TpaPlusPlus/assets/50048293/c4db023d-f5b4-40a3-ace0-1003c2e35591)
It should be `windupData.getPlayers()[0]` not `windupData.getPlayers()[1]`

**Comment by SuperRicky14** [comment]
Merged, sorry you had to deal with my spaghetti code lol.
